name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels: ['feat', 'feature', 'enhancement']
  - title: 'Bug Fixes'
    labels: ['fix', 'bug']
  - title: 'Code Changes'
    labels: ['refactor', 'style', 'perf', 'revert']
  - title: 'Tests'
    labels: ['test']
  - title: 'Maintenance'
    labels: ['chore', 'ci', 'docs', 'build']
  - title: 'Breaking Changes'
    labels: ['major']

change-template: '- $TITLE ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['feat', 'feature']
  patch:
    labels: ['fix', 'chore', 'refactor', 'style', 'perf', 'test', 'docs', 'ci', 'build', 'revert']
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
