export const FILTER_KIND = {
  RANGE: 'RANGE',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  MULTI_SELECT_WITH_SEARCH: 'MULTI_SELECT_WITH_SEARCH',
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  SWITCH: 'SWITCH',
} as const;
