import type { JobListItemSchema } from '../schemas';
import type { JobStackTitle } from '../job-stack';
import type { JobListItemDto } from '../server/dtos/job-list-item.dto';

export const makeJob = (id: string): JobListItemSchema => ({
  id,
  title: `Engineer ${id}`,
  href: `/engineer-acme/${id}`,
  hasApplyUrl: true,
  classification: 'engineering',
  summary: 'Build useful things.',
  location: 'Amsterdam',
  locationType: 'hybrid',
  addresses: null,
  infoTags: [],
  tags: [],
  availability: [],
  organization: {
    name: 'Acme',
    href: '/o-acme~org-acme',
    websiteUrl: 'https://acme.example',
    location: 'Amsterdam',
    logo: null,
    employeeCount: null,
    summary: null,
    description: null,
    socials: null,
    projects: [],
    fundingRounds: [],
    investors: [],
    fundingStage: null,
    recentlyFunded: false,
    teamCoverageStatus: null,
    teamSignalsAsOf: null,
    currentMaintainerCount: null,
    activeLeadCount: null,
    newActiveLeadCount: null,
    steppedDownLeadCount: null,
    movedLeadCount: null,
    earlyLeadDepartureCount: null,
    intelligenceUrl:
      'https://ecosystem.vision/organizations/info/acme~org-acme',
  },
  timestampText: '2 hours ago',
  datePosted: '2026-09-29',
  badge: null,
});

export const jobTitles = (jobs: JobListItemSchema[]): JobStackTitle[] =>
  jobs.map(({ id, title, href, location }) => ({ id, title, href, location }));

export const makeJobDto = (id = 'job-1'): JobListItemDto => ({
  id: `db-${id}`,
  shortUUID: id,
  title: `Engineer ${id}`,
  url: 'https://acme.example/apply',
  timestamp: 1_700_000_000_000,
  summary: 'Build useful things.',
  seniority: null,
  salary: null,
  minimumSalary: null,
  maximumSalary: null,
  location: 'Amsterdam',
  locationType: 'hybrid',
  commitment: null,
  paysInCrypto: null,
  offersTokenAllocation: null,
  salaryCurrency: null,
  classification: 'engineering',
  workArrangement: null,
  tags: [],
  access: 'public',
  featured: false,
  featureStartDate: null,
  featureEndDate: null,
  onboardIntoWeb3: false,
  organization: {
    id: 'org-acme',
    orgId: 'org-acme',
    name: 'Acme',
    normalizedName: 'acme',
    website: 'https://acme.example',
    logoUrl: null,
    headcountEstimate: null,
    fundingRounds: [],
    investors: [],
  },
  project: null,
});
