name: Sync Draft Release with package.json

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: read

jobs:
  sync_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from package.json
        id: pkg
        run: |
          VERSION="v$(jq -r .version package.json)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Update Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          name: 'Next Release'
          tag: 'next-release'
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
